import Foundation

enum AppIcon {
    static let home = "house.fill"
    static let calendar = "calendar"
    static let search = "magnifyingglass"
    static let bulky = "sofa.fill"
    static let settings = "gearshape.fill"
    static let district = "mappin.and.ellipse"
    static let notification = "bell.badge.fill"
    static let update = "arrow.triangle.2.circlepath"
    static let official = "link"
    static let warning = "exclamationmark.triangle.fill"
    static let success = "checkmark.circle.fill"
    static let error = "xmark.octagon.fill"
    static let empty = "tray"
    static let info = "info.circle.fill"
    static let time = "clock.fill"
    static let bag = "bag.fill"
    static let today = "sun.max.fill"
    static let tomorrow = "sparkles"
    static let next = "arrow.forward.circle.fill"
    static let area = "map.fill"
    static let lightMode = "sun.max.circle.fill"
    static let celebration = "party.popper.fill"
    static let shield = "checkmark.shield.fill"
    static let officialCheck = "doc.text.magnifyingglass"
}
